# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(800, 600)
        LoginForm.setMinimumSize(QtCore.QSize(800, 600))
        LoginForm.setMaximumSize(QtCore.QSize(800, 600))
        LoginForm.setStyleSheet("QMainWindow {background-color:rgb(255, 255, 255)}\n"
"QPushButton {background-color:rgb(249, 249, 249);  color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC;}\n"
"QPushButton:hover {background-color:rgb(230, 230, 230);}\n"
"QPushButton:pressed {background-color:rgb(212, 212, 212);}\n"
"QLineEdit {padding: 5; border-radius: 10px;border: 1px solid #CCCCCC;font: 25 14pt \"Yu Gothic UI Light\";}\n"
"QLabel {color:rgb(28, 94, 217,);}")
        self.centralwidget = QtWidgets.QWidget(LoginForm)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 70, 240, 50))
        self.label.setStyleSheet("font: 25 36pt \"Yu Gothic UI Light\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 301, 61))
        self.label_2.setStyleSheet("font: 25 36pt \"Yu Gothic UI Light\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(355, 210, 90, 30))
        self.label_3.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(355, 290, 90, 30))
        self.label_4.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_4.setObjectName("label_4")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(260, 370, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color:rgb(255, 55, 118);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.sign_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_button.setGeometry(QtCore.QRect(340, 430, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sign_in_button.setFont(font)
        self.sign_in_button.setObjectName("sign_in_button")
        self.password_in = QtWidgets.QLineEdit(self.centralwidget)
        self.password_in.setGeometry(QtCore.QRect(320, 320, 160, 40))
        self.password_in.setStyleSheet("QLineEdit {border-radius: 10px;border: 1px solid #CCCCCC;font: 25 8pt \"Yu Gothic UI Light\";}")
        self.password_in.setText("")
        self.password_in.setObjectName("password_in")
        self.login_in = QtWidgets.QLineEdit(self.centralwidget)
        self.login_in.setGeometry(QtCore.QRect(320, 240, 160, 40))
        self.login_in.setText("")
        self.login_in.setObjectName("login_in")
        self.to_sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.to_sign_up_button.setGeometry(QtCore.QRect(300, 490, 211, 23))
        self.to_sign_up_button.setStyleSheet("QPushButton\n"
"{border: 0;\n"
"padding: 0;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 25 12pt \"Yu Gothic UI Semibold\";\n"
"color:rgb(28, 94, 217)}\n"
"QPushButton:hover {color: rgb(20, 69, 182);}\n"
"QPushButton:pressed {color: rgb(16, 58, 148);}\n"
"")
        self.to_sign_up_button.setObjectName("to_sign_up_button")
        LoginForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "MainWindow"))
        self.label.setText(_translate("LoginForm", "Welcome to"))
        self.label_2.setText(_translate("LoginForm", "corporate chat"))
        self.label_3.setText(_translate("LoginForm", "Username"))
        self.label_4.setText(_translate("LoginForm", "Password"))
        self.sign_in_button.setText(_translate("LoginForm", "Sign in"))
        self.to_sign_up_button.setText(_translate("LoginForm", "Don\'t have account? Sign up!"))
