# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chats = QtWidgets.QListWidget(self.centralwidget)
        self.chats.setGeometry(QtCore.QRect(10, 10, 256, 781))
        self.chats.setObjectName("chats")
        self.suitable_users = QtWidgets.QComboBox(self.centralwidget)
        self.suitable_users.setGeometry(QtCore.QRect(280, 40, 911, 20))
        self.suitable_users.setObjectName("suitable_users")
        self.find_user = QtWidgets.QLineEdit(self.centralwidget)
        self.find_user.setGeometry(QtCore.QRect(280, 10, 911, 20))
        self.find_user.setObjectName("find_user")
        self.messages = QtWidgets.QListWidget(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(280, 70, 911, 721))
        self.messages.setObjectName("messages")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
