# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(800, 600)
        RegisterForm.setMinimumSize(QtCore.QSize(800, 600))
        RegisterForm.setMaximumSize(QtCore.QSize(800, 600))
        RegisterForm.setStyleSheet("QMainWindow {background-color:rgb(255, 255, 255)}\n"
"QPushButton {background-color:rgb(249, 249, 249);  color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC;}\n"
"QPushButton:hover {background-color:rgb(230, 230, 230);}\n"
"QPushButton:pressed {background-color:rgb(212, 212, 212);}\n"
"QLineEdit {border-radius: 10px;border: 1px solid #CCCCCC;}\n"
"QLabel {color:rgb(28, 94, 217,);}")
        self.centralwidget = QtWidgets.QWidget(RegisterForm)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(335, 70, 131, 50))
        self.label.setStyleSheet("font: 25 36pt \"Yu Gothic UI Light\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 300, 61))
        self.label_2.setStyleSheet("font: 25 36pt \"Yu Gothic UI Light\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(355, 210, 90, 30))
        self.label_3.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(355, 290, 90, 30))
        self.label_4.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_4.setObjectName("label_4")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(350, 370, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color:rgb(255, 55, 118);")
        self.error_label.setObjectName("error_label")
        self.sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up_button.setGeometry(QtCore.QRect(340, 450, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setObjectName("sign_up_button")
        self.password_in = QtWidgets.QLineEdit(self.centralwidget)
        self.password_in.setGeometry(QtCore.QRect(320, 320, 160, 40))
        self.password_in.setObjectName("password_in")
        self.login_in = QtWidgets.QLineEdit(self.centralwidget)
        self.login_in.setGeometry(QtCore.QRect(320, 240, 160, 40))
        self.login_in.setObjectName("login_in")
        RegisterForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "MainWindow"))
        self.label.setText(_translate("RegisterForm", "Join to"))
        self.label_2.setText(_translate("RegisterForm", "corporate chat"))
        self.label_3.setText(_translate("RegisterForm", "Username"))
        self.label_4.setText(_translate("RegisterForm", "Password"))
        self.error_label.setText(_translate("RegisterForm", "rr"))
        self.sign_up_button.setText(_translate("RegisterForm", "Sign up"))
