# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(800, 600)
        RegisterForm.setMinimumSize(QtCore.QSize(800, 600))
        RegisterForm.setMaximumSize(QtCore.QSize(800, 600))
        RegisterForm.setStyleSheet("QMainWindow {background-color:rgb(255, 255, 255)}\n"
"QPushButton {background-color:rgb(249, 249, 249);  color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC;}\n"
"QPushButton:hover {background-color:rgb(230, 230, 230);}\n"
"QPushButton:pressed {background-color:rgb(212, 212, 212);}\n"
"QLineEdit {border-radius: 10px;border: 1px solid #CCCCCC; font: 25 14pt \"Yu Gothic UI Light\";}\n"
"QLabel {color:rgb(28, 94, 217,);}")
        self.centralwidget = QtWidgets.QWidget(RegisterForm)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(335, 30, 131, 50))
        self.label.setStyleSheet("font: 25 32pt \"Yu Gothic UI Light\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 70, 300, 61))
        self.label_2.setStyleSheet("font: 25 32pt \"Yu Gothic UI Light\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 240, 90, 30))
        self.label_3.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(355, 320, 90, 30))
        self.label_4.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_4.setObjectName("label_4")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(260, 400, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color:rgb(255, 55, 118);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up_button.setGeometry(QtCore.QRect(340, 470, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setObjectName("sign_up_button")
        self.password_in = QtWidgets.QLineEdit(self.centralwidget)
        self.password_in.setGeometry(QtCore.QRect(320, 350, 160, 40))
        self.password_in.setStyleSheet("QLineEdit {border-radius: 10px;border: 1px solid #CCCCCC;font: 25 8pt \"Yu Gothic UI Light\";}")
        self.password_in.setObjectName("password_in")
        self.email_in = QtWidgets.QLineEdit(self.centralwidget)
        self.email_in.setGeometry(QtCore.QRect(320, 270, 160, 40))
        self.email_in.setObjectName("email_in")
        self.to_login_button = QtWidgets.QPushButton(self.centralwidget)
        self.to_login_button.setGeometry(QtCore.QRect(340, 530, 121, 23))
        self.to_login_button.setStyleSheet("QPushButton\n"
"{border: 0;\n"
"padding: 0;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 25 12pt \"Yu Gothic UI Semibold\";\n"
"color:rgb(28, 94, 217)}\n"
"QPushButton:hover {color: rgb(20, 69, 182);}\n"
"QPushButton:pressed {color: rgb(16, 58, 148);}\n"
"")
        self.to_login_button.setObjectName("to_login_button")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(355, 160, 90, 30))
        self.label_5.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.label_5.setObjectName("label_5")
        self.login_in = QtWidgets.QLineEdit(self.centralwidget)
        self.login_in.setGeometry(QtCore.QRect(320, 190, 160, 40))
        self.login_in.setText("")
        self.login_in.setObjectName("login_in")
        RegisterForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "MainWindow"))
        self.label.setText(_translate("RegisterForm", "Join to"))
        self.label_2.setText(_translate("RegisterForm", "corporate chat"))
        self.label_3.setText(_translate("RegisterForm", "Email"))
        self.label_4.setText(_translate("RegisterForm", "Password"))
        self.sign_up_button.setText(_translate("RegisterForm", "Sign up"))
        self.to_login_button.setText(_translate("RegisterForm", "Back to login"))
        self.label_5.setText(_translate("RegisterForm", "Username"))
